upload_max_filesize = 100M
post_max_size = 100M
memory_limit = 512M
max_execution_time = 120
max_input_time = 120

date.timezone = UTC
display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT


extension=pdo_pgsql
extension=pgsql
extension=redis
extension=zip
extension=bcmath
